# Generated by Django 4.2.3 on 2023-07-23 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
    ]
