# Generated by Django 4.2.3 on 2023-07-24 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0002_remove_ticket_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
    ]
