# Generated by Django 4.2.3 on 2023-07-24 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0003_alter_journey_options_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["journey", "wagon_number", "seat_number"]},
        ),
    ]
